BUG FOUND
Depositing of trash. bug fround
In disposal area. Press 'E' to empty dust bag.
UnityEngine.Debug:Log (object)
Roomba_Player:OnTriggerEnter (UnityEngine.Collider) (at Assets/Scripts/Roomba/Roomba_Player.cs:241)

In disposal area. Press 'E' to empty dust bag.
UnityEngine.Debug:Log (object)
Roomba_Player:OnTriggerEnter (UnityEngine.Collider) (at Assets/Scripts/Roomba/Roomba_Player.cs:241)

NullReferenceException: Object reference not set to an instance of an object
Roomba_Player+<BagEmptying>d__46.MoveNext () (at Assets/Scripts/Roomba/Roomba_Player.cs:401)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <493b407efcb64dddad59f28bb0b831d3>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Roomba_Player:HandleDisposalInput() (at Assets/Scripts/Roomba/Roomba_Player.cs:151)
Roomba_Player:Update() (at Assets/Scripts/Roomba/Roomba_Player.cs:76)